appmantenimiento/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mantenimientoSLOGIN.urls')),
    path('panel/', include('mantenimientoReportes.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mantenimientoReportes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.panel, name='panel'),
    path('nueva_maquina/', views.nueva_maquina, name='nueva_maquina'), 
    path('modificar_maquina/<int:maquina_id>/', views.modificar_maquina, name='modificar_maquina'),
    path('eliminar_maquina/<int:maquina_id>/', views.eliminar_maquina, name='eliminar_maquina'),

    path('partes', views.partes, name='partes'), 
    path('partes/modificar_partes/<int:parte_id>/', views.modificar_partes, name='modificar_partes'),
    path('partes/eliminar_partes/<int:parte_id>/', views.eliminar_partes, name='eliminar_partes'),

    path('inventario_entrada/', views.inventario_entrada, name='inventario_entrada'),
    path('inventario_entrada/editar/<int:inventario_id>/', views.editar_inventario_entrada, name='editar_inventario_entrada'),
    path('inventario_entrada/eliminar/<int:inventario_id>/', views.eliminar_inventario_entrada, name='eliminar_inventario_entrada'),

    path('mantenimiento/', views.mantenimiento, name='mantenimiento'),
    path('mantenimiento/editar/<int:mantenimiento_id>/', views.editar_mantenimiento, name='editar_mantenimiento'),
    path('mantenimiento/eliminar/<int:mantenimiento_id>/', views.eliminar_mantenimiento, name='eliminar_mantenimiento'),

    path('mantenimiento_partes/obtener_inventario_disponible/<int:parte_id>/', views.obtener_inventario_disponible, name='obtener_inventario_disponible'),

    path('almacen/', views.almacen, name='almacen'),
]

mantenimientoReportes/models.py
from django.contrib.auth import get_user_model
from django.db import models
import qrcode
import os
from io import BytesIO
from django.core.files import File
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver
import os
from decimal import Decimal
from django.core.files.storage import default_storage
from appmantenimiento import settings
from mantenimientoSLOGIN.models import Usuario 



class Maquina(models.Model):
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    maquina = models.TextField(max_length=100)
    marca = models.TextField(max_length=100)
    modelo = models.TextField(max_length=100)
    horas_maquina = models.DecimalField(max_digits=10, decimal_places=2)
    nombre_maquina = models.TextField(max_length=100, blank=True, editable=False)
    foto_maquina = models.ImageField(upload_to='maquinas/', null=True, blank=True)
    qr = models.ImageField(upload_to='qr/', null=True, blank=True)

    def save(self, *args, **kwargs):
        # Elimina la imagen anterior si ha cambiado
        if self.pk:
            maquina_db = Maquina.objects.get(pk=self.pk)
            if maquina_db.foto_maquina != self.foto_maquina:
                ruta_anterior = os.path.join(settings.MEDIA_ROOT, str(maquina_db.foto_maquina))
                if os.path.isfile(ruta_anterior):
                    os.remove(ruta_anterior)

        # Construir el nombre de la máquina antes de guardar
        self.nombre_maquina = f"{self.maquina} {self.marca} {self.modelo}"

        super().save(*args, **kwargs)

class CatalogoPartes(models.Model):
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nombre_partes = models.TextField(max_length=100)
    numero_partes = models.TextField(max_length=20)
    horas_vida = models.DecimalField(max_digits=10, decimal_places=2)
    costo_aproximado = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    foto_partes = models.ImageField(upload_to='partes/', null=True, blank=True)
    maquinas = models.ManyToManyField(Maquina, related_name='partes')
    

    def save(self, *args, **kwargs):
        # Elimina la imagen anterior si ha cambiado
        if self.pk:
            parte_db = CatalogoPartes.objects.get(pk=self.pk)
            if parte_db.foto_partes != self.foto_partes:
                ruta_anterior = os.path.join(settings.MEDIA_ROOT, str(parte_db.foto_partes))
                if os.path.isfile(ruta_anterior):
                    os.remove(ruta_anterior)

        super(CatalogoPartes, self).save(*args, **kwargs)

class MovimientoInventario(models.Model):
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    maquinas = models.ForeignKey(Maquina, on_delete=models.CASCADE, null=True, blank=True)
    partes = models.ForeignKey(CatalogoPartes, on_delete=models.CASCADE)
    piezas_entrada = models.PositiveIntegerField(null=True, blank=True)
    piezas_salida = models.PositiveIntegerField(blank=True, null=True)
    fecha_entrada = models.DateTimeField(auto_now_add=True)
    fecha_salida = models.DateTimeField(auto_now_add=True)
    costo_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_piezas = models.IntegerField(default=0)
    new_horas_maquina = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    movimiento = models.BooleanField(default=True)

    def __str__(self):
        tipo_movimiento = "Entrada" if self.movimiento else "Salida"
        return f"{self.maquinas} - {self.partes.nombre_partes} - {tipo_movimiento}: {self.piezas_entrada}"

mantenimientoReportes/forms.py
import qrcode
from django import forms
from .models import CatalogoPartes, Maquina, MovimientoInventario
from django.core.files import File
from io import BytesIO

class MaquinaForm(forms.ModelForm):
    class Meta:
        model = Maquina
        fields = ['maquina', 'marca', 'modelo', 'horas_maquina', 'foto_maquina']

class CatalogoPartesForm(forms.ModelForm):
    class Meta:
        model = CatalogoPartes
        fields = ['nombre_partes', 'numero_partes', 'horas_vida', 'foto_partes', 'costo_aproximado']
        
class InventarioEntradaForm(forms.ModelForm):
    class Meta:
        model = MovimientoInventario
        fields = ['partes', 'piezas_entrada']
        

class InventarioSalidaForm(forms.ModelForm):
    class Meta:
        model = MovimientoInventario
        fields = ['maquinas', 'partes', 'piezas_salida', 'new_horas_maquina']

mantenimientoReportes/views.py
from datetime import datetime, timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
from django.contrib.auth.decorators import user_passes_test,login_required
from django.http import Http404, HttpResponse, HttpResponseBadRequest, JsonResponse
from appmantenimiento import settings
from .forms import InventarioEntradaForm, InventarioSalidaForm,MaquinaForm, CatalogoPartesForm
from mantenimientoSLOGIN.models import Usuario  # Asegúrate de importar tu modelo de usuario
from .models import Maquina, CatalogoPartes, MovimientoInventario
from django.shortcuts import get_object_or_404, redirect, render
from django.core.files.storage import default_storage
from django.contrib import messages
from django.db.models import Sum
from django.db.models import F
from django.db.models import Max
from django.db import transaction

# Decorador para permitir solo a los administradores
@user_passes_test(lambda u: u.is_authenticated and u.tipo_usuario == 'administrador', login_url='/iniciar_sesion/')
def panel(request):
    maquinas = Maquina.objects.filter(user=request.user)
    nombre_usuario = request.user.username  # Cambia esto según tu modelo de Usuario
    
    if request.method == 'POST':
        form = MaquinaForm(request.POST, request.FILES)
        if form.is_valid():
            maquina = form.save(commit=False)
            maquina.user = request.user  # Asigna el usuario actual
            maquina.save()
            return redirect('panel')
    else:
        form = MaquinaForm()
    
    
    context = {'form': MaquinaForm(),'maquinas': maquinas, 'nombre_usuario': nombre_usuario}
    return render(request, 'panel.html', context)

@login_required
def nueva_maquina(request):
    if request.method == 'POST':
        form = MaquinaForm(request.POST, request.FILES)
        if form.is_valid():
            maquina = form.save(commit=False)
            maquina.user = request.user  # Asigna el usuario actual
            maquina.save()
            return redirect('panel')
    else:
        form = MaquinaForm()
    context = {'form': form}
    return render(request, 'nueva_maquina.html', context)

@login_required
def modificar_maquina(request, maquina_id):
    maquina = get_object_or_404(Maquina, pk=maquina_id)

    if request.method == "POST":
        print(request.POST)
        form = MaquinaForm(request.POST, request.FILES, instance=maquina)
        if form.is_valid():
            form.save()
            maquina.refresh_from_db()  # Actualiza la instancia desde la base de datos
            return redirect('panel')

    else:
        form = MaquinaForm(instance=maquina)

    return render(request, 'modificar_maquina.html', {'form': form, 'maquina': maquina})


@login_required
def eliminar_maquina(request, maquina_id):
    try:
        maquina = Maquina.objects.get(id=maquina_id)
    except Maquina.DoesNotExist:
        raise Http404("La máquina que intentas eliminar no existe.")
    
    if request.method == 'POST':
        if maquina.foto_maquina:
            if os.path.isfile(maquina.foto_maquina.path):
                os.remove(maquina.foto_maquina.path)
        maquina.delete()
        messages.success(request, 'La máquina ha sido eliminada exitosamente.')
        return redirect('panel')
    
    maquinas = Maquina.objects.filter(user=request.user)  # Agrega esto para obtener la lista actualizada de máquinas
    context = {'maquinas': maquinas}
    return render(request, 'panel.html', context)

@login_required
def partes(request):
    partes = CatalogoPartes.objects.filter(user=request.user)
    nombre_usuario = request.user.username

    if request.method == 'POST':
        form = CatalogoPartesForm(request.POST, request.FILES)
        if form.is_valid():
            parte = form.save(commit=False)
            parte.user = request.user
            parte.save()
            return redirect('partes')
    else:
        form = CatalogoPartesForm()

    context = {'form': form, 'partes': partes, 'nombre_usuario': nombre_usuario}
    return render(request, 'partes.html', context)



@login_required
def modificar_partes(request, parte_id):
    parte = get_object_or_404(CatalogoPartes, pk=parte_id)

    if request.method == "POST":
        form = CatalogoPartesForm(request.POST, request.FILES, instance=parte)
        if form.is_valid():
            form.save()
            parte.refresh_from_db()
            return redirect('partes')
    else:
        form = CatalogoPartesForm(instance=parte)

    return render(request, 'modificar_partes.html', {'form': form, 'parte': parte})

@login_required
def eliminar_partes(request, parte_id):
    try:
        parte = CatalogoPartes.objects.get(id=parte_id)
    except CatalogoPartes.DoesNotExist:
        raise Http404("La parte que intentas eliminar no existe.")

    if request.method == 'POST':
        if parte.foto_partes:
            if os.path.isfile(parte.foto_partes.path):
                os.remove(parte.foto_partes.path)
        parte.delete()
        messages.success(request, 'La parte ha sido eliminada exitosamente.')
        return redirect('partes')

    partes = CatalogoPartes.objects.filter(user=request.user)
    context = {'partes': partes}
    return render(request, 'partes.html', context)


@login_required
def inventario_entrada(request):
    inventario = MovimientoInventario.objects.filter(user=request.user, movimiento=True)
    partes = CatalogoPartes.objects.all()

    if request.method == 'POST':
        form = InventarioEntradaForm(request.POST)
        if form.is_valid():
            inventario_item = form.save(commit=False)
            inventario_item.user = request.user
            inventario_item.movimiento = True  # Indicar que es un movimiento de entrada
            inventario_item.entrada = datetime.now(timezone.utc)
            inventario_item.save()
            # Recuperar el objeto después de guardarlo
            inventario_item = get_object_or_404(MovimientoInventario, id=inventario_item.id)

            # Obtener el objeto relacionado a través de partes
            partes_obj = inventario_item.partes

            # Obtener el último movimiento relacionado con la misma parte
            ultimo_movimiento = MovimientoInventario.objects.filter(user=request.user, partes=partes_obj, movimiento=True).exclude(id=inventario_item.id).last()

            # Obtener el total_piezas del último movimiento o establecerlo en 0 si no hay movimientos previos
            total_piezas_anterior = ultimo_movimiento.total_piezas if ultimo_movimiento else 0

            # Actualizar total_piezas
            inventario_item.total_piezas = total_piezas_anterior + inventario_item.piezas_entrada
            inventario_item.save()

            print(f"partes: {inventario_item.partes}, piezas_entrada: {inventario_item.piezas_entrada}, total_piezas después del guardado: {inventario_item.total_piezas}")

            return redirect('inventario_entrada')
    else:
        form = InventarioEntradaForm()

        # Agregar paginación
    paginator = Paginator(inventario, 10)  # Muestra 10 entradas por página
    page = request.GET.get('page')

    try:
        inventario_pagina = paginator.page(page)
    except PageNotAnInteger:
        inventario_pagina = paginator.page(1)
    except EmptyPage:
        inventario_pagina = paginator.page(paginator.num_pages)

    context = {'inventario': inventario, 'form': form, 'partes': partes, 'inventario_pagina': inventario_pagina}
    return render(request, 'inventario_entrada.html', context)

@login_required
def editar_inventario_entrada(request, inventario_id):
    inventario = get_object_or_404(MovimientoInventario, pk=inventario_id, user=request.user, movimiento=True)

    if request.method == "POST":
        form = InventarioEntradaForm(request.POST, instance=inventario)
        if form.is_valid():
            inventario = form.save(commit=False)
            inventario.movimiento = True  # Asegurarse de que se mantiene como un movimiento de entrada
            inventario.save()
            return redirect('inventario_entrada')

    else:
        form = InventarioEntradaForm(instance=inventario)

    return render(request, 'editar_inventario.html', {'form': form, 'inventario_item': inventario})

@login_required
def eliminar_inventario_entrada(request, inventario_id):
    inventario = get_object_or_404(MovimientoInventario, id=inventario_id, user=request.user, movimiento=True)
    
    if request.method == 'POST':
        inventario.delete()
        return redirect('inventario_entrada')

    return render(request, 'eliminar_inventario.html', {'inventario': inventario})

@login_required
def mantenimiento(request):
    mantenimiento_items = MovimientoInventario.objects.filter(user=request.user, movimiento=False)
    partes = CatalogoPartes.objects.all()
    maquinas = Maquina.objects.all()

    if request.method == 'POST':
        form = InventarioSalidaForm(request.POST)
        if form.is_valid():
            mantenimiento_item = form.save(commit=False)
            mantenimiento_item.user = request.user
            mantenimiento_item.movimiento = False  # Indicar que es un movimiento de salida (mantenimiento)
            mantenimiento_item.fecha_salida = datetime.now(timezone.utc)# Actualizar la fecha de entrada
            mantenimiento_item.save()
            
            mantenimiento_item = get_object_or_404(MovimientoInventario, id=mantenimiento_item.id)

            # Obtener el objeto relacionado a través de partes
            partes_obj = mantenimiento_item.partes

            # Obtener el último movimiento relacionado con la misma parte
            ultimo_movimiento = MovimientoInventario.objects.filter(user=request.user, partes=partes_obj, movimiento=True).exclude(id=mantenimiento_item.id).last()

            # Obtener el total_piezas del último movimiento o establecerlo en 0 si no hay movimientos previos
            total_piezas_anterior = ultimo_movimiento.total_piezas if ultimo_movimiento else 0

mantenimientoReportes/templates/almacen.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container py-5">
    <section class="card card-body text-center">
        <h1 class="text-center mt-4">Almacen de Partes</h1>
    </section>
    <p></p>
    <div class="col">

    </div>
    <p></p>
    <section class="card card-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Foto Parte</th>
                        <th>Nombre de Parte</th>
                        <th>Numero de Parte</th>
                        <th>Total de piezas</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in partes %}
                        <tr>
                            <td>
                                {% if item.foto_partes %}
                                    <img src="{{ item.foto_partes.url }}" alt="Foto de Parte" style="max-width: 100px; max-height: 100px;">
                                {% else %}
                                    No disponible
                                {% endif %}
                            </td>
                            <td>{{ item.nombre_partes }}</td>
                            <td>{{ item.numero_partes }}</td>
                            <td>
                                {% with total_piezas=0 %}
                                    {% for movimiento in item.movimientoinventario_set.all %}
                                        {% if not movimiento.movimiento %}
                                            {% with total_piezas=total_piezas|add:movimiento.piezas_salida %}
                                            {% endwith %}
                                        {% endif %}
                                    {% endfor %}
                                    {{ total_piezas }}
                                {% endwith %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if almacen_pagina.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ almacen_pagina.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Página {{ almacen_pagina.number }} de {{ almacen_pagina.paginator.num_pages }}.
                </span>

                {% if almacen_pagina.has_next %}
                    <a href="?page={{ almacen_pagina.next_page_number }}">next</a>
                    <a href="?page={{ almacen_pagina.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>

</main>
{% endblock %}

mantenimientoReportes/templates/eliminar_reporte.html
{% extends 'base.html' %}

{% block content %}
  <h1>Eliminas reporte</h1>
  <p>¿Estás seguro de que deseas eliminar el reporte "{{ reporte.titulo }}"?</p>
  
  <form method="POST" action="{% url 'eliminar_reporte' reporte.id_reporte %}">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Sí">
    <a class="btn btn-primary" href="{% url 'reportes' %}">No</a>
  </form>
{% endblock %}

mantenimientoReportes/templates/mantenimiento.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container py-5">
    <section class="card card-body text-center">
        <h1 class="text-center mt-4">Mantenimiento de Maquinas</h1>
    </section>
    <p></p>
    <div class="col">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#nuevoMantenimientoModal" >
            <i class="fa-solid fa-plus" style="color: #ffffff;"></i> Nueva Mantenimiento
        </button>
    </div>
    <p></p>
    <section class="card card-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Foto Maquina</th>
                    <th>Nombre de Maquina</th>
                    <th>Nueva hora de Maquina</th>
                    <th>Foto Parte</th>
                    <th>Nombre de Parte</th>
                    <th>Numero de Parte</th>
                    <th>Piezas de Salida</th>
                    <th>Fecha de Salida</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                {% for item in mantenimiento_items %}
                    <tr>
                    <td>
                        {% if item.maquinas.foto_maquina %}
                        <img src="{{ item.maquinas.foto_maquina.url }}" alt="Foto de Maquina" style="max-width: 100px; max-height: 100px;">
                        {% else %}
                        No disponible
                        {% endif %}
                    </td>
                    <td>{{ item.maquinas.nombre_maquina }}</td>
                    <td>{{ item.new_horas_maquina}}</td>
                    <td>
                        {% if item.partes.foto_partes %}
                        <img src="{{ item.partes.foto_partes.url }}" alt="Foto de Parte" style="max-width: 100px; max-height: 100px;">
                        {% else %}
                        No disponible
                        {% endif %}
                    </td>
                    <td>{{ item.partes.nombre_partes }}</td>
                    <td>{{ item.partes.numero_partes }}</td>
                    <td>{{ item.piezas_salida}}</td>
                    <td>{{ item.fecha_salida}}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Acciones">
                                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editarMantenimientoModal{{ item.id }}" >
                                    <i class="fa-solid fa-pencil" style="color: #ffffff;"></i>
                                </button>
                                <a href="#" class="btn btn-danger" onclick="eliminarInventario('{{ item.id }}')">
                                    <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
                                </a>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if mantenimiento_pagina.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ mantenimiento_pagina.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Página {{ mantenimiento_pagina.number }} de {{ mantenimiento_pagina.paginator.num_pages }}.
                </span>

                {% if mantenimiento_pagina.has_next %}
                    <a href="?page={{ mantenimiento_pagina.next_page_number }}">next</a>
                    <a href="?page={{ mantenimiento_pagina.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>

    <div class="modal fade" id="nuevoMantenimientoModal" tabindex="-1" aria-labelledby="nuevoMantenimientoModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="nuevoMantenimientoModalLabel">Nueva Mantenimiento</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="maquinas">Maquina:</label>
                        <select class="form-control " name="maquinas" id="maquinas" required>
                            <option></option>
                            {% for maquina in maquinas %}
                                <option value="{{ maquina.id }}">{{ maquina.nombre_maquina }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="PartesMantenimiento">Parte:</label>
                        <select class="form-control" name="partes" id="PartesMantenimiento" required>
                            <option></option>
                            {% for parte in partes %}
                                <option value="{{ parte.id }}" {% if parte.id == parte_seleccionada.id %}selected{% endif %}>
                                    {{ parte.nombre_partes }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="piezas_salida">Piezas de salida:</label>
                        <input type="number" id="piezas_salida" class="form-control" name="piezas_salida"  >
                    </div>
                    <div class="mb-3">
                        <label for="cantidad_disponible">Cantidad disponible:</label>
                        <span id="cantidad_disponible">{{ cantidad_disponible }}</span>
                    </div>
                    <div class="mb-3">
                        <label for="new_horas_maquina">Nueva hora:</label>
                        <input type="number" id="new_horas_maquina" class="form-control" name="new_horas_maquina"  >
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
                
            </div>
            
        </div>
        </div>
    </div>


    {% if mantenimientos %}
    {% for mantenimiento in mantenimientos %}
    <div class="modal fade" id="editarMantenimientoModal{{ mantenimiento.id }}" tabindex="-1" aria-labelledby="editarMantenimientoModalLabel{{ mantenimiento.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="editarMantenimientoModal{{ mantenimiento.id }}">Modificar Mantenimiento</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="{% url 'editar_mantenimiento' mantenimiento_id=mantenimiento.id%}" enctype="multipart/form-data" id="editarMantenimientoForm{{ mantenimiento.id }}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="SelectMaquinaMantenimiento">Maquina:</label>
                    <select class="form-control" name="maquina" id="SelectMaquinaMantenimiento" required>
                        <option value="" {% if not mantenimiento.maquina %}selected{% endif %}></option>
                        {% for maquina in maquinas %}
                            <option value="{{ maquina.id }}" {% if mantenimiento.maquina and mantenimiento.maquina.id == maquina.id %}selected{% endif %}>
                                {{ maquina.nombre_maquina }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="id_piezas_salida">Piezas de salida:</label>
                    <input type="number" id="id_piezas_salida" class="form-control" name="piezas_salida">
                    {% if form.errors.piezas_salida %}
                        <small class="text-danger">{{ form.errors.piezas_salida.0 }}</small>
                    {% endif %}
                    {% if form.instance.inventario %}
                        <small class="text-info">Cantidad disponible: {{ form.instance.inventario.total_piezas }}</small>
                    {% endif %}
                </div>
                <div class="mb-3">
                    <label for="piezas_salida">Piezas de salida:</label>
                    <input type="number" id="piezas_salida" class="form-control" name="piezas_salida" required value="{{ mantenimiento.piezas_salida }}">
                </div>
                <div class="mb-3">
                    <label for="new_horas_maquina">Horas de maquina:</label>
                    <input type="number" id="new_horas_maquina" class="form-control"name="new_horas_maquina" required value="{{ mantenimiento.hrs }}">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    </div>
    {% endfor %}
    {% endif %}


    <script>
        function eliminarInventario(itemId) {
        var confirmar = confirm("¿Estás seguro de que deseas eliminar este inventario?");
        if (confirmar) {
            // Agregamos un campo oculto para enviar el maquina_id en el formulario POST
            var form = document.createElement('form');
            form.method = 'post';
            form.action = "{% url 'eliminar_mantenimiento' mantenimiento_id=0 %}".replace('0', itemId);
            form.style.display = 'none';
            
            var csrfTokenInput = document.createElement('input');
            csrfTokenInput.type = 'hidden';
            csrfTokenInput.name = 'csrfmiddlewaretoken';
            csrfTokenInput.value = "{{ csrf_token }}";
            
            form.appendChild(csrfTokenInput);
            document.body.appendChild(form);
            
            form.submit();
        }
        }
    </script>
    
</main>
{% endblock %}

mantenimientoReportes/templates/nueva_tabla.html
{% extends 'base.html' %}

{% block content %}
<h1>Crear Nueva Tabla</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Crear Tabla</button>
</form>
{% endblock %}